### ISSUE TITLE
Breadcrumb link styling missing

### ISSUE THREAD

**Issue by stephajn** [jnprr/blazor-breadcrumb-navigation#2] opened 2021-09-01 17:39 UTC
I followed the directions for getting started with the component and I can indeed see my breadcrumb links appearing.  However, it seems that styling information is missing for the ul and li elements that render the breadcrumb itself. Looking at the sample on the GitHub page, it looks like there's a css file that is supposed to be getting used, but I don't see any reference to that in any of my rendered pages. Is this something that hasn't made it into the final release yet?

**Comment by cschulzsuper** [comment] 2021-09-02 04:57
I'm not sure which CSS file you are referring to, but I have to admit, that I left something out of the getting started guide.

The default style of the breadcrumbs is included via Blazors CSS isolation. By doing it this way, the CSS will never interfere with another CSS on the page. The style of the breadcrumbs is automatically merged into the CSS of the application. In the example this application CSS is added in the `index.html`.

``` html
<link href="BlazorWebAssembly.styles.css" rel="stylesheet" />
```

Please let me know if that might be the cause of your problem. I will then update the getting started guide accordingly.

**Comment by cschulzsuper** [comment] 2021-09-10 17:30
I'm closing this issue, since there was not response.

**Closed as completed by cschulzsuper** 2021-09-10 17:30 UTC
